version: "3"

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '172.16.94.182'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://172.16.94.182'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /root/khoatd/gitlab/config:/etc/gitlab
